### ISSUE TITLE
Getting version on Android started to fail

### ISSUE THREAD

**Issue by kmkrtich** [kimxogus/react-native-version-check#110]
Started from today my Android version checker is failing.

  console.log('LATEST VERSION ANDROID: ', await VersionCheck.getLatestVersion({
    provider: 'playStore'
  }));

It returns just dot  ' . '

Also using needUpdate fails :
 
const isNeeded = await VersionCheck.needUpdate({ depth: 2 });

I'm getting warning : TypeError : Invalid Version .0.0

I'm using 3.4.0 version
And my application version in playstore is 1.31.2

**Comment by bohdansushchak** [comment]
same

"react-native-version-check": "^3.4.0",
"react": "16.8.6",
"react-native": "0.60.6",

**Comment by TadjerouniMohamedAdel** [comment]
same issue

**Comment by xGum** [comment]
same issue

**Comment by kimxogus** [comment]
Fixed by #111 and https://github.com/kimxogus/react-native-version-check/releases/tag/v3.4.1 is published.

**Comment by razorabhu1995** [comment]
i think it is not fixed yet!!! @kimxogus 

I am still getting the error

**Comment by khoand0407** [comment]
i still see this error on v3.4.1 please check it

**Comment by joartola** [comment]
Have same problem here 
"react-native-version-check": "^3.4.0"

**Comment by jayeshkarma100** [comment]
still the same issue  with
    "react-native-version-check": "^3.4.2",

**Comment by AndreyMirzoyan** [comment]
same problem, ^3.4.2

**Comment by penghouho** [comment]
For me, I had the problem at 3.3.0 and fixed after updated to 3.4.2
