### ISSUE TITLE
i'm new at this

### ISSUE THREAD

**Issue by porknoodles** [kimxogus/react-native-version-check#5]
```
checkVersion(){
      VersionCheck.setAppID('123456789');
      VersionCheck.setAppName('awesomeproject');

      platformCheck = Platform.OS === 'ios' ? 'https://www.google.com/' : 'https://www.bing.com/',
      curVersion = VersionCheck.getCurrentVersion()
      console.log('this is current version ========-=-=-=-=-=-=-=-=-=-=-=-= ', VersionCheck.getCurrentVersion())
      VersionCheck.getLatestVersion({
          forceUpdate: true,
          url: "https://www.bing.com/version",   // this url contain number for latestversion
      }).then(latestVersion =>{
          VersionCheck.needUpdate({
              currentVersion: curVersion, // curversion is 2.0 
              latestVersion: latestVersion // latestversion is 10
          }).then(res => {
            console.log('this is latest version -=-=-=-=-=-=-=-=-=- ', latestVersion)
              if (res.isNeeded) {
                  Alert.alert(
                      'you need to bloody update',
                      'new version bloody available',
                      [{
                          text: 'Bloody Upgrade',
                          onPress: () => {
                              Linking.openURL(platformCheck)
                          }
                      }]
                  )
              }
          })
      });
  }
```

so the function i put inside componentwillmount() and it didn't budge!!
where have I done wrong?
i think it read 10 as 1.0

**Comment by kimxogus** [comment]
Does it throw an error? or prints nothing?
If there's an error thrown, please share it

**Comment by porknoodles** [comment]
no errors, it just printed out the console log
'this is current version -=-=-=-=-=-=-=-=-=- ', '2.0'
'this is latest version -=-=-=-=-=-=-=-=-=- ', '10'

**Comment by kimxogus** [comment]
Try '10.0' version as usually contains dot characters

**Comment by kimxogus** [comment]
Anyway, it seems that version checking doesn't work properly when the version doesn't contain `.`.
This will be resolved soon.

**Comment by kimxogus** [comment]
Please check again. I fixed some code related with this issue.

**Comment by porknoodles** [comment]
```
platformCheck = Platform.OS === 'ios' ? 'http://json.org/example.html' : 'http://json.org/example.html',
      curVersion = VersionCheck.getCurrentVersion()
      console.log('this is current version -=-=-=-=-=-=-=-=-=- ', curVersion) // 'this is current version -=-=-=-=-=-=-=-=-=- ', '2.0'
     
      VersionCheck.getLatestVersion({
          forceUpdate: true,
          url: "http://json.org/example.html", 
      }).then(latestVersion =>{
          VersionCheck.needUpdate({
              currentVersion: curVersion,
              latestVersion: latestVersion
          }).then(res => {
            console.log('this is latest version -=-=-=-=-=-=-=-=-=- ', latestVersion) //'this is latest version -=-=-=-=-=-=-=-=-=- ', '10.0'
              if (res.isNeeded) {
                  Alert.alert(
                      'NEW UPDATE IS AVAILABLE',
                      'PLEASE PRESS UPGRADE',
                      [{
                          text: 'Upgrade',
                          onPress: () => {
                              Linking.openURL(platformCheck)
                          }
                      }]
                  )
              }
          })
      });
```
latestVersion 10.0 and 20.0
still can't give me any alert, although in my package.json i get
"react-native-version-check": "1.2.2", instead of "react-native-version-check": "1.2.0",

**Comment by kimxogus** [comment]
I found the error and fixed it.
Please check again with version `1.3.0`.

**Comment by porknoodles** [comment]
work like a charm!!
thank you!!!
